name: Reusable Workflow

on:
  workflow_call:
    inputs:
      deploy_to:
        required: true
        type: string

jobs:
  deploy:
    runs-on: windows-latest
    environment: ${{ inputs.deploy_to }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Az PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          Get-InstalledModule -Name Az  # Verify installation

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          az extension add --name databricks

      - name: Debug Azure Secrets
        shell: pwsh
        run: |
          Write-Host "Deploying to ${{ inputs.deploy_to }} environment"

      - name: Authenticate with Azure using PowerShell
        shell: pwsh
        run: |
          $secureSecret = ConvertTo-SecureString "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential("${{ secrets.AZURE_CLIENT_ID }}", $secureSecret)
          Connect-AzAccount -ServicePrincipal -TenantId "${{ secrets.AZURE_TENANT_ID }}" -Credential $creds

      - name: Deploy to Databricks
        env:
          DATABRICKS_HOST: ${{ inputs.deploy_to == 'PROD' && secrets.DATABRICKS_PROD_HOST || secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ inputs.deploy_to == 'PROD' && secrets.DATABRICKS_PROD_TOKEN || secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          databricks workspace import_dir --overwrite notebooks /Workspace/notebooks
