name: Reusable Workflow

on:
  workflow_call:
    inputs:
      deploy_to:
        required: true
        type: string
      databricks_host:
        required: true
        type: string
      databricks_token:
        required: true
        type: string
      azure_client_secret:
        required: true
        type: string
      azure_client_id:
        required: true
        type: string
      azure_tenant_id:
        required: true
        type: string
    secrets: # This is the crucial part: declare the secrets
      DATABRICKS_DEV_HOST:
        required: true # Or false, depending on if it's optional
      DATABRICKS_DEV_TOKEN:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      DATABRICKS_PROD_HOST:
        required: true
      DATABRICKS_PROD_TOKEN:
        required: true
jobs:
  deploy:
    runs-on: windows-latest
    environment: DEV_WORKSPACE_NAME
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Az PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          Get-InstalledModule -Name Az

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          az extension add --name databricks

      - name: Authenticate with Azure using PowerShell
        shell: pwsh
        run: |
          $secureSecret = ConvertTo-SecureString "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential("${{ secrets.AZURE_CLIENT_ID }}", $secureSecret)
          Connect-AzAccount -ServicePrincipal -TenantId "${{ secrets.AZURE_TENANT_ID }}" -Credential $creds

      - name: Deploy Notebooks to ${{ inputs.deploy_to }} Environment
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }} # Access secrets here
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }} # Access secrets here
        run: |
          databricks workspace import_dir --overwrite notebooks /Workspace/notebooks
