name: Reusable Workflow

on:
  workflow_call:
    inputs:
      deploy_to:
        required: true
        type: string
    secrets:
      databricks_host:
        required: true
      databricks_token:
        required: true
      azure_client_secret:
        required: true
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true

jobs:
  deploy:
    runs-on: windows-latest
    environment: ${{ inputs.deploy_to }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Az PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          Get-InstalledModule -Name Az  # Verify installation

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          az extension add --name databricks

      - name: Debug Azure Secrets
        shell: pwsh
        run: |
          Write-Host "Deploying to ${{ inputs.deploy_to }} environment"
          Write-Host "DATABRICKS_HOST: ${{ secrets.databricks_host }}"
          Write-Host "AZURE_CLIENT_ID: ${{ secrets.azure_client_id }}"
          Write-Host "AZURE_TENANT_ID: ${{ secrets.azure_tenant_id }}"

      - name: Authenticate with Azure using PowerShell
        shell: pwsh
        run: |
          $secureSecret = ConvertTo-SecureString "${{ secrets.azure_client_secret }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential("${{ secrets.azure_client_id }}", $secureSecret)
          Connect-AzAccount -ServicePrincipal -TenantId "${{ secrets.azure_tenant_id }}" -Credential $creds

      - name: Deploy Notebooks to ${{ inputs.deploy_to }} Environment
        env:
          DATABRICKS_HOST: ${{ secrets.databricks_host }}
          DATABRICKS_TOKEN: ${{ secrets.databricks_token }}
        run: |
          databricks workspace import_dir --overwrite notebooks /Workspace/notebooks
