name: SonarQube Analysis and Deployment

on:
  push:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pytest pytest-cov coverage

      - name: Convert Notebooks to Python scripts
        run: |
          jupyter nbconvert --to script notebooks/*.ipynb --output-dir notebooks
          for file in notebooks/*.txt; do
            mv "$file" "${file%.txt}.py"
          done
          ls notebooks

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)/notebooks" >> $GITHUB_ENV

      - name: Run Tests with Coverage
        run: |
          pytest tests --cov=notebooks --cov-report=xml

      - name: Run SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin"
          sonar-scanner -Dsonar.projectKey=databricks_project \
                        -Dsonar.projectName=DatabricksProject \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=notebooks \
                        -Dsonar.python.coverage.reportPaths=coverage.xml \
                        -Dsonar.python.version=3.x \
                        -Dsonar.host.url=http://20.55.75.25:9000 \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deployToDatabricksDev:
    needs: sonarQubeAnalysis
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set Secrets as Env Vars
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_DEV_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_DEV_TOKEN }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Run Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          deploy_to: "DEV_WORKSPACE_NAME"
          databricks_host: ${{ env.DATABRICKS_HOST }}
          databricks_token: ${{ env.DATABRICKS_TOKEN }}
          azure_client_secret: ${{ env.AZURE_CLIENT_SECRET }}
          azure_client_id: ${{ env.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ env.AZURE_TENANT_ID }}

  deployToDatabricksProd:
    needs: deployToDatabricksDev
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set Secrets as Env Vars
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_PROD_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_PROD_TOKEN }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Run Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          deploy_to: "PROD_WORKSPACE_NAME"
          databricks_host: ${{ env.DATABRICKS_HOST }}
          databricks_token: ${{ env.DATABRICKS_TOKEN }}
          azure_client_secret: ${{ env.AZURE_CLIENT_SECRET }}
          azure_client_id: ${{ env.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
