name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      # Convert .ipynb notebooks to .py
      - name: Convert Notebooks to Python scripts
        run: |
          jupyter nbconvert --to script notebooks/*.ipynb --output-dir notebooks

          # Rename .txt files to .py
          for file in notebooks/*.txt; do
            mv "$file" "${file%.txt}.py"
          done
          
          # Verify the result
          ls notebooks
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)/notebooks" >> $GITHUB_ENV

      # Run SonarScanner
      - name: Run SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin"
          sonar-scanner -Dsonar.projectKey=databricks_project \
                        -Dsonar.projectName=DatabricksProject \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=notebooks \
                        -Dsonar.host.url=http://20.55.75.25:9000 \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
