name: SonarQube Analysis and Deployment

on:
  push:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pytest pytest-cov coverage

      # Convert .ipynb notebooks to .py
      - name: Convert Notebooks to Python scripts
        run: |
          jupyter nbconvert --to script notebooks/*.ipynb --output-dir notebooks
          # Rename .txt files to .py
          for file in notebooks/*.txt; do
            mv "$file" "${file%.txt}.py"
          done
          # Verify the result
          ls notebooks

      # Set PYTHONPATH
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)/notebooks" >> $GITHUB_ENV

      # Run Tests with Coverage
      - name: Run Tests with Coverage
        run: |
          pytest tests --cov=notebooks --cov-report=xml

      # Run SonarScanner
      - name: Run SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin"
          sonar-scanner -Dsonar.projectKey=databricks_project \
                        -Dsonar.projectName=DatabricksProject \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=notebooks \
                        -Dsonar.python.coverage.reportPaths=coverage.xml \
                        -Dsonar.python.version=3.x \
                        -Dsonar.host.url=http://20.55.75.25:9000 \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  
  deployToDatabricksDev:
    runs-on: windows-latest
    needs: sonarQubeAnalysis
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 1: Install Az PowerShell Module with Timeout
      - name: Install Az PowerShell Module
        shell: pwsh
        timeout-minutes: 10
        run: |
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          Get-InstalledModule -Name Az  # Verify installation

      # Install Databricks CLI
      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          az extension add --name databricks

      # PowerShell Script for Authentication
      - name: Authenticate with Azure using PowerShell
        shell: pwsh
        run: |
          $secureSecret = ConvertTo-SecureString "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential("${{ secrets.AZURE_CLIENT_ID }}", $secureSecret)
          Connect-AzAccount -ServicePrincipal -TenantId "${{ secrets.AZURE_TENANT_ID }}" -Credential $creds

      - name: Deploy Notebooks to Dev Environment
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          databricks workspace import_dir notebooks /Workspace/notebooks

  deployToDatabricksProd:
    runs-on: windows-latest
    needs: deployToDatabricksDev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 1: Install Az PowerShell Module with Timeout
      - name: Install Az PowerShell Module
        shell: pwsh
        timeout-minutes: 10
        run: |
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          Get-InstalledModule -Name Az  # Verify installation

      # Install Databricks CLI
      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          az extension add --name databricks

      # PowerShell Script for Authentication
      - name: Authenticate with Azure using PowerShell
        shell: pwsh
        run: |
          $secureSecret = ConvertTo-SecureString "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential("${{ secrets.AZURE_CLIENT_ID }}", $secureSecret)
          Connect-AzAccount -ServicePrincipal -TenantId "${{ secrets.AZURE_TENANT_ID }}" -Credential $creds

      - name: Deploy Notebooks to Prod Environment
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        run: |
          databricks workspace import_dir notebooks /Workspace/notebooks
